### ISSUE TITLE
Add author info

### ISSUE THREAD

**Issue by WuYen** [WuYen/dividendLeap.v2#4]
## Task

- [x] Prerequire
  - Aim one author
    - WADE0616

- [x] Get author [標的] post
  - Get latest 3 if possible
  - Figure out [標的] post's target stock object
  - Get stock price after posting base on following if possible.
    - [post day, two weeks, one month, two months ] 

- [x] Add author info link to notify
  - Update processMessage function

- [x] Nice to have
    - [x] When specific user post [標的], save it to somewhere
    - [x] Design cache, for performance
    - [ ] ~~Maybe create a job to maintain cache~~
